plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.6'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.jyujyu.dayonetest'
version = '0.0.1-SNAPSHOT'
description = 'day-one-test'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'

    runtimeOnly 'com.mysql:mysql-connector-j'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    testImplementation 'org.testcontainers:testcontainers:1.19.0'

    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    testImplementation 'com.redis.testcontainers:testcontainers-redis-junit:1.6.4'

    implementation 'org.springframework.boot:spring-boot-starter-kafka'
    testImplementation 'org.testcontainers:kafka:1.19.0'

    implementation(platform('software.amazon.awssdk:bom:2.20.136'))
    implementation 'commons-io:commons-io:2.13.0'
    implementation 'software.amazon.awssdk:aws-core'
    implementation 'software.amazon.awssdk:sdk-core'
    implementation 'software.amazon.awssdk:sts'
    implementation 'software.amazon.awssdk:s3'
    testImplementation 'org.testcontainers:localstack:1.19.0'
}

tasks.named('test') {
    useJUnitPlatform()
}
